name: Liquibase RDS Migration

on:
  push:
    branches:
      - liquibase
  workflow_dispatch:

jobs:
  liquibase-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Liquibase Update
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.db-username }}
          DB_PASSWORD: ${{ secrets.db-password }}
          CHANGELOG_PATH: "src/main/resources/db/changelog.yaml"
        run: |
          ./mvnw liquibase:update \
            -Dliquibase.url="${{ secrets.DB_URL }}" \
            -Dliquibase.username="${{ secrets.db-username }}" \
            -Dliquibase.password="${{ secrets.db-password }}" \
            -Dliquibase.changeLogFile="src/main/resources/db/changelog.yaml"
